### ISSUE TITLE
Getting OutOfMemory exception when try to run a HelloWorld java file 

### ISSUE THREAD

**Issue by kekkaishivn** [lsds/sgx-lkl#32]
Hi,

I am trying to install sgx-lkl and run a modified simple java file with socket programming and get this exception: 
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/j2re-image/lib/amd64/libnet.so: Error loading shared library /opt/j2re-image/lib/amd64/libnet.so: Out of memory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at java.net.AbstractPlainSocketImpl$1.run(AbstractPlainSocketImpl.java:84)
	at java.net.AbstractPlainSocketImpl$1.run(AbstractPlainSocketImpl.java:82)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.AbstractPlainSocketImpl.<clinit>(AbstractPlainSocketImpl.java:81)
	at java.net.ServerSocket.setImpl(ServerSocket.java:288)
	at java.net.ServerSocket.<init>(ServerSocket.java:230)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at HelloWorld.main(HelloWorld.java:16

Is it caused by the constrainted memory inside enclave. Do u know how I can tune the parameters to run it. I run the programme in hardware mode in Linux 16.04. Here is the hello world java file: 

import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Date;

/**
 * A simple TCP server. When a client connects, it sends the client the current
 * datetime, then closes the connection. This is arguably the simplest server
 * you can write. Beware though that a client has to be completely served its
 * date before the server will be able to handle another client.
 */
public class HelloWorld {
    public static void main(String[] args) throws IOException {
        try  {
            ServerSocket listener = new ServerSocket(59090);
            System.out.println("The date server is running...");
            while (true) {
                try  {
                    Socket socket = listener.accept();
                    PrintWriter out = new PrintWriter(socket.getOutputStream(), true);
                    out.println(new Date().toString());
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
        }
    }
}

**Comment by cpriebe** [comment]
You can increase the size of the enclave heap via `SGXLKL_HEAP`. By default, `sgx-lkl-java`, which is just a wrapper around `sgx-lkl-run` sets the heap size to 256MB. Try something like

`SGXLKL_HEAP=512M <sgx-lkl>/tools/sgx-lkl-java mydisk.img <java args>`

Depending on what your application does/requires you might also have to change some of the preconfigured JVM runtime parameters specified in `sgx-lkl-java` like the code cache size (current default `-XX:ReservedCodeCacheSize=4000K`) or the compressed class space size (current default `-XX:CompressedClassSpaceSize=4000K`).

**Comment by kekkaishivn** [comment]
Thanks, it works !!!
