### ISSUE TITLE
[Tests] /tmp filesystem does not have xattr or user xattr support

### ISSUE THREAD

**Issue by vamsikrishna935** [lsds/sgx-lkl#736]
Testcase: lgetxattr02
```
#0  setup () at lgetxattr02.c:84
#1  0x00007fe03da63450 in do_test_setup () at tst_test.c:890
#2  testrun () at tst_test.c:1003
#3  fork_testrun () at tst_test.c:1132
#4  0x00007fe03da640d2 in tst_run_tcases (argc=<optimized out>, argv=<optimized out>, self=self@entry=0x7fe03dc79080 <test>)
    at tst_test.c:1203
#5  0x00007fe03da60510 in main (argc=<optimized out>, argv=<optimized out>) at ../../../../include/tst_test.h:284
#6  0x00007fe00052e56c in libc_start_main_stage2 (main=0x7fe03da60500 <main>, argc=1, argv=0x7fe040afef80)
    at src/env/__libc_start_main.c:168
#7  0x00007fe00052e4c6 in __libc_start_main (main=0x7fe03da60500 <main>, argc=1, argv=0x7fe040afef80)
    at src/env/__libc_start_main.c:153
#8  0x00007fe03da6054e in _start_c (p=<optimized out>) at crt/crt1.c:17
#9  0x00007fe03da60526 in _start ()
#10 0x00007fe040afefa0 in ?? ()
#11 0x0000000000000001 in ?? ()
#12 0x00007fe000b007a0 in ?? ()
#13 0x0000000000000000 in ?? ()
(gdb) n
(gdb)
lgetxattr02.c:78: CONF: no xattr support in fs or mounted without user_xattr option
```

**Comment by paulcallen** [comment]
@prp has suggested we may not want to support this attribute on /tmp. Needs a triage discussion to determine if this is a by-design or P2/P3
